package com.hanclouds.model.carmanage;

import com.alibaba.fastjson.annotation.JSONField;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class ProCardInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.operator_name
     *
     * @mbg.generated
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.msisdn
     *
     * @mbg.generated
     */
    private String msisdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.iccid
     *
     * @mbg.generated
     */
    private String iccid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.imsi
     *
     * @mbg.generated
     */
    private String imsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.open_date
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date openDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.active_date
     *
     * @mbg.generated
     */
    private Date activeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.card_status
     *
     * @mbg.generated
     */
    private String cardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.belong_area
     *
     * @mbg.generated
     */
    private String belongArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.net_type
     *
     * @mbg.generated
     */
    private String netType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.offering_id
     *
     * @mbg.generated
     */
    private String offeringId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.pro_key
     *
     * @mbg.generated
     */
    private String proKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.sale_charges
     *
     * @mbg.generated
     */
    private BigDecimal saleCharges;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.sale_years
     *
     * @mbg.generated
     */
    private Double saleYears;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.triffc_use
     *
     * @mbg.generated
     */
    private Double triffcUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.triffc_all
     *
     * @mbg.generated
     */
    private Double triffcAll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_card_info.due_time
     *
     * @mbg.generated
     */
    private Date dueTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pro_card_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.id
     *
     * @return the value of pro_card_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.id
     *
     * @param id the value for pro_card_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.operator_name
     *
     * @return the value of pro_card_info.operator_name
     *
     * @mbg.generated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.operator_name
     *
     * @param operatorName the value for pro_card_info.operator_name
     *
     * @mbg.generated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.msisdn
     *
     * @return the value of pro_card_info.msisdn
     *
     * @mbg.generated
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.msisdn
     *
     * @param msisdn the value for pro_card_info.msisdn
     *
     * @mbg.generated
     */
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn == null ? null : msisdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.iccid
     *
     * @return the value of pro_card_info.iccid
     *
     * @mbg.generated
     */
    public String getIccid() {
        return iccid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.iccid
     *
     * @param iccid the value for pro_card_info.iccid
     *
     * @mbg.generated
     */
    public void setIccid(String iccid) {
        this.iccid = iccid == null ? null : iccid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.imsi
     *
     * @return the value of pro_card_info.imsi
     *
     * @mbg.generated
     */
    public String getImsi() {
        return imsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.imsi
     *
     * @param imsi the value for pro_card_info.imsi
     *
     * @mbg.generated
     */
    public void setImsi(String imsi) {
        this.imsi = imsi == null ? null : imsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.open_date
     *
     * @return the value of pro_card_info.open_date
     *
     * @mbg.generated
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.open_date
     *
     * @param openDate the value for pro_card_info.open_date
     *
     * @mbg.generated
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.active_date
     *
     * @return the value of pro_card_info.active_date
     *
     * @mbg.generated
     */
    public Date getActiveDate() {
        return activeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.active_date
     *
     * @param activeDate the value for pro_card_info.active_date
     *
     * @mbg.generated
     */
    public void setActiveDate(Date activeDate) {
        this.activeDate = activeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.comment
     *
     * @return the value of pro_card_info.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.comment
     *
     * @param comment the value for pro_card_info.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.card_status
     *
     * @return the value of pro_card_info.card_status
     *
     * @mbg.generated
     */
    public String getCardStatus() {
        return cardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.card_status
     *
     * @param cardStatus the value for pro_card_info.card_status
     *
     * @mbg.generated
     */
    public void setCardStatus(String cardStatus) {
        this.cardStatus = cardStatus == null ? null : cardStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.belong_area
     *
     * @return the value of pro_card_info.belong_area
     *
     * @mbg.generated
     */
    public String getBelongArea() {
        return belongArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.belong_area
     *
     * @param belongArea the value for pro_card_info.belong_area
     *
     * @mbg.generated
     */
    public void setBelongArea(String belongArea) {
        this.belongArea = belongArea == null ? null : belongArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.net_type
     *
     * @return the value of pro_card_info.net_type
     *
     * @mbg.generated
     */
    public String getNetType() {
        return netType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.net_type
     *
     * @param netType the value for pro_card_info.net_type
     *
     * @mbg.generated
     */
    public void setNetType(String netType) {
        this.netType = netType == null ? null : netType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.offering_id
     *
     * @return the value of pro_card_info.offering_id
     *
     * @mbg.generated
     */
    public String getOfferingId() {
        return offeringId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.offering_id
     *
     * @param offeringId the value for pro_card_info.offering_id
     *
     * @mbg.generated
     */
    public void setOfferingId(String offeringId) {
        this.offeringId = offeringId == null ? null : offeringId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.pro_key
     *
     * @return the value of pro_card_info.pro_key
     *
     * @mbg.generated
     */
    public String getProKey() {
        return proKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.pro_key
     *
     * @param proKey the value for pro_card_info.pro_key
     *
     * @mbg.generated
     */
    public void setProKey(String proKey) {
        this.proKey = proKey == null ? null : proKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.sale_charges
     *
     * @return the value of pro_card_info.sale_charges
     *
     * @mbg.generated
     */
    public BigDecimal getSaleCharges() {
        return saleCharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.sale_charges
     *
     * @param saleCharges the value for pro_card_info.sale_charges
     *
     * @mbg.generated
     */
    public void setSaleCharges(BigDecimal saleCharges) {
        this.saleCharges = saleCharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.sale_years
     *
     * @return the value of pro_card_info.sale_years
     *
     * @mbg.generated
     */
    public Double getSaleYears() {
        return saleYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.sale_years
     *
     * @param saleYears the value for pro_card_info.sale_years
     *
     * @mbg.generated
     */
    public void setSaleYears(Double saleYears) {
        this.saleYears = saleYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.triffc_use
     *
     * @return the value of pro_card_info.triffc_use
     *
     * @mbg.generated
     */
    public Double getTriffcUse() {
        return triffcUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.triffc_use
     *
     * @param triffcUse the value for pro_card_info.triffc_use
     *
     * @mbg.generated
     */
    public void setTriffcUse(Double triffcUse) {
        this.triffcUse = triffcUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.triffc_all
     *
     * @return the value of pro_card_info.triffc_all
     *
     * @mbg.generated
     */
    public Double getTriffcAll() {
        return triffcAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.triffc_all
     *
     * @param triffcAll the value for pro_card_info.triffc_all
     *
     * @mbg.generated
     */
    public void setTriffcAll(Double triffcAll) {
        this.triffcAll = triffcAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_card_info.due_time
     *
     * @return the value of pro_card_info.due_time
     *
     * @mbg.generated
     */
    public Date getDueTime() {
        return dueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_card_info.due_time
     *
     * @param dueTime the value for pro_card_info.due_time
     *
     * @mbg.generated
     */
    public void setDueTime(Date dueTime) {
        this.dueTime = dueTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_card_info
     *
     * @mbg.generated
     */

}